java_binary(
    name = "ConfigureVSC",
    main_class = "com.salesforce.bazel.ide.vsc.ConfigureVSC",
    srcs = glob(["src/main/java/**/*.java"]),
    deps = [
      "//sdk/bazel-java-sdk",
    ]
)

# TODO java_test
